# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Matcha < Formula
  desc "A beautiful and functional email client for your terminal."
  homepage "https://matcha.floatpane.com"
  version "0.16.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/floatpane/matcha/releases/download/v0.16.2/matcha_0.16.2_darwin_amd64.tar.gz"
      sha256 "be38518f3853a130f9ac40ae34109ea487b2cda899ad8495752a96bf8a3ec877"

      def install
        bin.install "matcha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/floatpane/matcha/releases/download/v0.16.2/matcha_0.16.2_darwin_arm64.tar.gz"
      sha256 "9c3b5f6ad313970d59322514ab1b96c7c07bba46a5e6aae328a45ca75639b990"

      def install
        bin.install "matcha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/floatpane/matcha/releases/download/v0.16.2/matcha_0.16.2_linux_amd64.tar.gz"
      sha256 "a6285a4ad3cf0e18ec86cff8871bcd20686324471dd80943b3636af169dab253"
      def install
        bin.install "matcha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/floatpane/matcha/releases/download/v0.16.2/matcha_0.16.2_linux_arm64.tar.gz"
      sha256 "ff51bf1ce35f6ed03f2169a80588aefaca6444bc76d74128830f7b558ab8924d"
      def install
        bin.install "matcha"
      end
    end
  end

  test do
    system "#{bin}/matcha --version"
  end
end
