# This file was generated by GoReleaser. DO NOT EDIT.
cask "matcha@v1" do
  version "1.0.0-rc1"

  on_macos do
    on_intel do
      sha256 "ba4bcc557dece1622cd70d3c2f364e33d780cfa771d5a33e57b20852c9ecd81c"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db315a7b5d433f90c4a6c0a05ec9f3e7073796d6cee924d37378a14a61c771da"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da763a900af50e497a4dc8b1d6ba5e8fd4407ac0a34d752e291809e94d138e07"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1fcb70d5cd4e6f6cdc1d928bf1bbb93e1e55ef1a10316af68bd56bc89112d3d"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_arm64.tar.gz"
    end
  end

  name "matcha@v1"
  desc "A beautiful and functional email client for your terminal."
  homepage "https://matcha.email"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matcha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matcha"]
    end
  end

  # No zap stanza required

end
