# This file was generated by GoReleaser. DO NOT EDIT.
cask "matcha" do
  version "0.40.1"

  on_macos do
    on_intel do
      sha256 "76b9b0babc53b83df638d04bc81d4fab87c1ed196023cc948d890f1e14dd40aa"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cea7ab67cfc0d9a83c74248a8a6462d5a44ef0cd63d60e8532689bd9db5eed49"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "473a8c6228d79deb5319607688e97eea236633ac2042e3170ae1032f493bacca"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9b16095773815afde20a6f2abf2951e80211e7d384dd479dc04eb54d82cbc1e"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_arm64.tar.gz"
    end
  end

  name "matcha"
  desc "A beautiful and functional email client for your terminal."
  homepage "https://matcha.email"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matcha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matcha"]
    end
  end

  # No zap stanza required

end
