# This file was generated by GoReleaser. DO NOT EDIT.
cask "matcha" do
  version "0.43.0"

  on_macos do
    on_intel do
      sha256 "e3a98574da645cc2049ffbc1e64493e867388e753767f7603256f335a83ad537"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8472800ebcb01284e5b2322ea8266aa41463d766688f9ab795007de78d9f0cea"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "51782176a720f0a11bbcc6cfcec7a065d05f9e8ee933d955f4fe616f9b403e35"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1848725eaf2df6bcef747536876a1fa69983d515d3c9f7bcfd2f63ba775c1f63"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_arm64.tar.gz"
    end
  end

  name "matcha"
  desc "A beautiful and functional email client for your terminal."
  homepage "https://matcha.email"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matcha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matcha"]
    end
  end

  # No zap stanza required

end
