# This file was generated by GoReleaser. DO NOT EDIT.
cask "matcha@v1" do
  version "1.0.0-rc2"

  on_macos do
    on_intel do
      sha256 "a4b8f47e3b8f20f21cdb62cfa9718db4932911d742ae68475553195e4cb83316"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "faba4e35b9bf01337b4493b43cb25dcbc73e3021cb4a6b14f6ebf33196a00a06"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4058472afe8cef95250ceac71e54fa8ad05be2fd30f4e107c48256da3f131d77"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcd82243273af43e995115a41c4dd89806812185feed6b2a92a4ba4d0f784d3b"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_arm64.tar.gz"
    end
  end

  name "matcha@v1"
  desc "A beautiful and functional email client for your terminal."
  homepage "https://matcha.email"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matcha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matcha"]
    end
  end

  # No zap stanza required

end
