# This file was generated by GoReleaser. DO NOT EDIT.
cask "matcha" do
  version "0.44.0"

  on_macos do
    on_intel do
      sha256 "52263ef438e13c61330cca646d2a4fe8f8e970ef75b2ec06e6396a7fa51289d3"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fbeedd481010cd1c7ddd62f1945eeaad6168d65bc1b46050ed7d02bc16f2f96"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "787e917fa72716c0630134862c7c74c39be20df61b40edd3a3e768effab83b51"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f73e50ffbb7d9a44c4595ef0fa96900db722e685914199a0296dde6d989fea8"
      url "https://github.com/floatpane/matcha/releases/download/v#{version}/matcha_#{version}_linux_arm64.tar.gz"
    end
  end

  name "matcha"
  desc "A beautiful and functional email client for your terminal."
  homepage "https://matcha.email"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matcha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matcha"]
    end
  end

  # No zap stanza required

end
